### ISSUE TITLE
Warp drive for limited time periods would be awesome.

### ISSUE THREAD

**Issue by ralphsaunders** [robhawkes/rawkets#3]
Just sayin'.

**Comment by savagemic** [comment]
Would be sweet!

**Comment by robhawkes** [comment]
The game universe is going to change quite dramatically in the final game. It will be bigger and there will potentially be more than one world (the area within the white boundaries). Because of this there will be a need for faster travel, so I will be implementing a way to speed your rocket up, like warp drive, or some sort of teleportation system to get from point A to B, or world to world, instantly.

**Comment by ralphsaunders** [comment]
I can't wait :D

**Comment by ralphsaunders** [comment]
I can't wait :D
